### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by ariG23498**
This PR helps with:
1. Some minor math typos
2. Adds a little para on the analogy of VAEs with each reverse diffusion process steps.

### CODE REVIEW

**Review by AakashKumarNain — APPROVED** [review]
Looks good. Have you tried building the web page locally with `quarto build` and check if the changes are okay?

**Comment by ariG23498** [comment]
Unfortunately I haven't.

**Comment by AakashKumarNain** [comment]
Can you quickly do that please, and probably put a screenshot here? Asking because there is no way to automatically test this on my end

**Comment by ariG23498** [comment]
image

image

image

**Comment by AakashKumarNain** [comment]
@ariG23498 sorry that I missed this earlier but your comment `We assume noisy image to be our latent..`, this is more applicable to a Denoising autoencoder, and that too a traditional autoencoder not a variational autoencoder

**Comment by ariG23498** [comment]
> @ariG23498 sorry that I missed this earlier but your comment `We assume noisy image to be our latent..`, this is more applicable to a Denoising autoencoder, and that too a traditional autoencoder not a variational autoencoder

Here I wanted to mean that we can consider each reverse step as a latent variable model in itself. This can be further expanded to a point where the process of getting the image (x_0) from the noisy image (x_T) is considered the chain of latent varaible models. Once we view the reverse process like so, we can easily build our intuition on why we would need the ELBO for optimization.

If I miscommunicated somewhere please let me know.

CC: @sayakpaul

**Comment by sayakpaul** [comment]
This might easily lead to confusion since there's a specific family of latent-space diffusion models where there's a separate VAE involved. Then there are pixel-space diffusion models. So, I agree with @AakashKumarNain's point.

**Comment by ariG23498** [comment]
@AakashKumarNain I have made the changes. I think this is in good shape to be merged. Let me know if you need anything else from my end.

**Review by sayakpaul — APPROVED** [review]

**Comment by AakashKumarNain** [comment]
Thanks folks!

**Pull request merged**
